addons:
  postgresql: 9.4
language: ruby
rbenv:
  - 2.4.5
services:
  - postgresql
  - redis-server
before_install:
  - gem install bundler
before_script:
  - bundle exec rake db:{drop,create,migrate,seed}
script:
  - bundle exec rspec
env:
  global:
    secure: PZRjJBt+UXIQu5TF9RoH7OuO7LhLK5tOB6vlh/b60lg/LMLsskQ/5V0tztEHZTVyvFFY/MWSBgYqy2lS4XENvQmKX0Pqg1qOKqGFSb0059lEB7f9EKJGBZ0hD+5Ck6w6+MQ8yfCAfpLh8DxQ2ZhCIORQ5uVPB/0SnIAvQ85PQ8JVV7mk4P0+xc+WWti3uWhrjkzhwC1P4rMEX8+3zw48UxKyecTAlD6kUBk0FqpyhuSFPTvvXhQQG1o/LLvYa8cRrSH9Z2Niy7Ad4xN+ZRouUbCfG2F2vmz4vBj3Np0A85BwxqQ7OQuYNKznJvKOy7j9kRHbWr8gJLX93ycdaeKjra2MmKqXzh0B1zu3c2g4ewNruJBkOqS9qpi7E+Xp844CmKkNiL1I1DcWXGqhFARdRl1xwzJFxxkeY1PM9MymAqvZoCFrrzAQDLGpWt5o45GEnilGxzZw/ndvM2sgxVIXn+JBq86A7MKJ/RY/+Qq9SUd43W7z7JLjRYT4Y9X8nllGAM7/Ak99kTzWIyDsHHQnFAT2GAD/9HtJyidZOLveDw7Bg8bU7HA/G040BMum9YyW7xwdy/KuxY6JfThkBi3wjZp51L8XG7msCVqBfaIyxVVG+JT1YkjNCMxaiGD7fMdU9a0dmfTKKLj+TH3xIv/YR617UV/0qNPv4kE20GGGvrQ=
