addons:
  postgresql: 9.4
language: ruby
rbenv:
- 2.4.5
services:
- postgresql
- redis-server
before_install:
- gem install bundler
before_script:
- bundle exec rake db:{drop,create,migrate}
script:
- bundle exec rspec
- bundle exec rake db:seed
deploy:
  provider: heroku
  api_key:
    secure: BRqF4PXTkPDf9ftpVWpAssqNjv6UZTJccDhqsK2w3qPwRQNr/CKWYaK2/QycEO2kHxI/Lof6JFKzvA4Iz6iC68UEI+csKs4J7CrDz+5oduIfBBLAEvdahmcKRulGovPF855MirW7X1XUymMtVW9Vkd6ZCcXNWrHnm7mUwXPWNKYHGJT9W8WqII9N7R9yL4ImIrvHCsDClrbStrbCR9AkQGvHDzSUM90aoDSIksPr80EC2VCY2Gh2MWql8Kqi817pPwQ9b2DumJY8Srf2vtz6IsbAobhSu37eZKV8ZfnHomMDtPl8Mw3NoOfLiSY4wO+loqA9FjKepknMEaFvPJYEl8QXvrEBf1MXeGYwXwQYH5KKU0r4PE2vGarAdZWuECiBw8jf4LXA1UuiilyauIzNCTe1NC0PfVoNJOuJ6gwBpMbatkNsvdgD3El5AFMQI3+oOlNcmu3SCUT2ZKd5plrdBIKLoDCblvbYnl1OZAAPazrxmZReD1DSlfleEWFVfZBF7zYecoAG8OspF8KtTkEga7SNxoyBmO2WUYSecjMffdFE1PzwWMyMKu5YulwB6/Nz49+O/caLyTHLRkLmpeU5e9C/fu4qPLieGcYW0XyW3wSn99ZQ5wMjAkG9RlnHEvUbhCcXn9nKhlAIjEaVLgaQU5O4DSfXJVNLIPS1UEVofzc=
